#GraphQL Endpoint: http://localhost:8080/graphql-schema-first
#GraphiQL Endpoint: http://localhost:8080/graphiql?path=/graphql-schema-first
spring:
  application.name: graphql-schema-first
  main.allow-circular-reference: true
  graphql:
    path: /graphql-schema-first
    graphiql.enabled: true

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: uat

---
spring.config.activate.on-profile: prod
