#GraphQL Endpoint: http://localhost:8080/graphql-completable
#GraphiQL Endpoint: http://localhost:8080/graphiql?path=/graphql-completable
spring:
  application.name: graphql-completable
  main.allow-circular-reference: true
  graphql:
    path: /graphql-completable
    graphiql.enabled: true

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: uat

---
spring.config.activate.on-profile: prod
